######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 26 14:23:55 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += gpio.c
